on:
  pull_request:
  push:
    tags-ignore:
      - '**'
    branches:
      - master

name: "Tests"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  tests:
    strategy:
      matrix:
        go-version: [latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}
      - name: Setup Node.js ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          curl -sLk https://raw.githubusercontent.com/kevincobain2000/cover-totalizer/master/install.sh | sh
      - name: Setup Node.js ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"

      - run: cd frontend; npm install
      - run: cd frontend; npm run check

      - run: cd frontend; npm run build
      - run: go mod tidy;go build -ldflags '-s -w' -o gol frontend/main.go
      - run: go mod tidy;go build
      - run: golangci-lint run ./...
      - run: go test -race -v ./... -count=1 -coverprofile=coverage.out

